---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
    storageClasses:
      - name: freenas-iscsi-csi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    driver:
      config:
        driver: freenas-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: ${SECRET_NAS_ADDR}
          port: 443
          apiKey: ${SECRET_NAS_API}
          allowInsecure: true
        sshConnection:
          host: ${SECRET_NAS_ADDR}
          port: 22
          username: csi
          password: csi
        zfs:
          cli:
            sudoEnabled: true
            paths:
              zfs: /usr/local/sbin/zfs
              zpool: /usr/local/sbin/zpool
              sudo: /usr/local/bin/sudo
              chroot: /usr/sbin/chroot
          datasetParentName: eldorado/iscsi/v
          detachedSnapshotsDatasetParentName: eldorado/iscsi/s
          # "" (inherit), lz4, gzip-9, etc
          zvolCompression:
          # "" (inherit), on, off, verify
          zvolDedup:
          zvolEnableReservation: false
          # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
          zvolBlocksize:
        iscsi:
          targetPortal: "${SECRET_NAS_ADDR}:3260"
          targetPortals: []
          # leave empty to omit usage of -I with iscsiadm
          interface:
          namePrefix: csi-
          nameSuffix: "-cluster"
          # add as many as needed
          targetGroups:
            # get the correct ID from the "portal" section in the UI
            - targetGroupPortalGroup: 1
              # get the correct ID from the "initiators" section in the UI
              targetGroupInitiatorGroup: 1
              # None, CHAP, or CHAP Mutual
              targetGroupAuthType: None
              # get the correct ID from the "Authorized Access" section of the UI
              # only required if using Chap
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 4096
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: "7200"
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0
