# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1VwmNeOPnMXp3JDm,iv:JXpN5AJyg4+H/MQDitlbceOnJzntTHvgl/Ff/tbqb4A=,tag:PVRtpGg02/hsPS7RK7MHGw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:r1CRu47+C2cpuZu7sfV8XLq8T+VMi8CHUkcK+boZug==,iv:I6wPWPD45zQtGULDq0+sOfrAe8cJqhKvT/DtezfjJWo=,tag:I6FqXOsH0ljv61yIeWHrXA==,type:str]
    SECRET_NAS_ADDR: ENC[AES256_GCM,data:oudUzdRVyxAM6on+,iv:97yasblnmV5LBWlH0fI15qoNz+8wabDLEYbIDbbORfM=,tag:H8BJECUQ2UZTXyWHgu0X9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bzdSS2VSOHlybWRFMHd2
            VE5HUUpvK3dJYnRhYXQ2a3Q0Y2FQT0Q5ZEdZClN6Wk9PTFViRFkzbVRDd2lxNTI4
            L3MzUDJCUW1EL2JhWmxRaEpuQXYya1UKLS0tIGphRXFBUGNZVTR3OXRPaHRuY0JU
            aW1yMy9DYTE4WTNlalJQcFBTSzVHUUEKIEWt9+LH5xF/4Wj2Fc3Ly8QU0xUt+8mF
            9q6pUWZm7VkFd6qzzIjGcfwEngTXZhu27teuUS+YVvVLNvNuadkB8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-19T15:46:24Z"
    mac: ENC[AES256_GCM,data:XPyRbkI/8Yy+bqMRPuThWmoLGwPQ95uAOMQJ0ljdk+3QCPDcHdkgZzeQPPAnv6AUc1Se2SnGtEEowIMx7wno/JX6wbZTz/nl1HFlFslxe8Dem+jDx9U58zM3dRKGSdPpf1O3tZm1BHZD2F39dvqLijKmi+ngRlHMOMwNcViXnIk=,iv:PhPo5Px+sj/Uqf+V7G8EbZqNvr1T3pddDgD3MFXR9nc=,tag:R2o2bJLMMg8Zqq5tMTDnSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
